In [ ]:
import numpy as np
print(np.__version__)

2.0.2


In [44]:
import numpy as np
x=22
data=np.array(x)
print("x:",x,type(x))
print("data:",data,type(data),"dimenssion:",data.ndim)

x: 22 <class 'int'>
data: 22 <class 'numpy.ndarray'> dimenssion: 0


In [ ]:
import numpy as np
x=[1,-3,2,-98]
data=np.array(x)
print("x:",x,type(x))
print("data:",data,type(data),"dimenssion:",data.ndim)

x: [1, -3, 2, -98] <class 'list'>
data: [  1  -3   2 -98] <class 'numpy.ndarray'> dimenssion: 1


In [42]:
import numpy as np
tempvalues_C = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 2, 0.1]
C = np.array(tempvalues_C)
print("temp in C")
print(C)
print("temp in F")
print(C * 9 / 5 + 32)

temp in C
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9  2.   0.1]
temp in F
[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 35.6  32.18]


In [43]:
fvalues = [ x*9/5 + 32 for x in tempvalues_C]
print(fvalues)

[68.18, 69.44, 71.42, 72.5, 72.86, 72.14, 71.24000000000001, 70.16, 69.62, 35.6, 32.18]


In [ ]:
import numpy as np
x=[[1,3,9],[10,-1,0.5],[1.9,16,11.2]]
data=np.array(x)
print("x:",x,type(x))
print("data:",data,type(data),"dimenssion:",data.ndim)


x: [[1, 3, 9], [10, -1, 0.5], [1.9, 16, 11.2]] <class 'list'>
data: [[ 1.   3.   9. ]
 [10.  -1.   0.5]
 [ 1.9 16.  11.2]] <class 'numpy.ndarray'> dimenssion: 2


In [46]:
#indexing & Slicing
import numpy as np
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print the first element of F
print(F[0])
# print the last element of F
print(F[-1])

1
21


In [47]:
A = np.array([ [3.4, 8.7, 9.9],
[1.1, -7.8, -0.7],
[4.1, 12.3, 4.8]])
print(A[1][0])

1.1


In [50]:
tmp = A[1]
print(tmp)
print(tmp[0])
print(A[1][0])
print(A[1, 0])

[ 1.1 -7.8 -0.7]
1.1
1.1
1.1


In [52]:
#The general syntax for a one-dimensional array A looks like this:
#A[start:stop:step]
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])
print(S[:])

[2 3 4]
[0 1 2 3]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [53]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])
print(A[:3, 2:])
print(A[:, 4:])

[[13 14 15]
 [23 24 25]
 [33 34 35]]


In [ ]:
#indexing
import numpy as np
x=[[1,4,9],[11,0.6,-11.8],[1.9,13,2]]
data=np.array(x)
print("x:",x,type(x),x[2][0])
print("data:",data,type(data),"dimenssion:",data.ndim,data[2,0])

x: [[1, 4, 9], [11, 0.6, -11.8], [1.9, 13, 2]] <class 'list'> 1.9
data: [[  1.    4.    9. ]
 [ 11.    0.6 -11.8]
 [  1.9  13.    2. ]] <class 'numpy.ndarray'> dimenssion: 2 1.9


In [ ]:
import numpy as np
x=[[1,4,9,10],[11,0.6,-11.8,8.3],[1.9,13,2,28],[0.1,13,-12,1]]
data=np.array(x)
y=data[1:3,1:3] # 2 * 2 matrix
z=data[1:,1:]
h=data[1::2,1::2] #step
m=data[1:4,2:4]
print(data.shape)
print(y)
print("----------------")
print(z)
print("----------------")
print(h)
print("----------------")
print(m)
print("----------------")

(4, 4)
[[  0.6 -11.8]
 [ 13.    2. ]]
----------------
[[  0.6 -11.8   8.3]
 [ 13.    2.   28. ]
 [ 13.  -12.    1. ]]
----------------
[[ 0.6  8.3]
 [13.   1. ]]
----------------
[[-11.8   8.3]
 [  2.   28. ]
 [-12.    1. ]]
----------------


In [ ]:
import numpy as np
x=[1,4,9,10,11,0.6,-11.8,8.3,1.9,13,2,28,0.1,13,-12,1]
data=np.array(x)
print(data.reshape(4,4))
print("----------------")
print(data.reshape(2,8))
print("----------------")
print(data.reshape(8,2))
print("----------------")
print(data)


[[  1.    4.    9.   10. ]
 [ 11.    0.6 -11.8   8.3]
 [  1.9  13.    2.   28. ]
 [  0.1  13.  -12.    1. ]]
----------------
[[  1.    4.    9.   10.   11.    0.6 -11.8   8.3]
 [  1.9  13.    2.   28.    0.1  13.  -12.    1. ]]
----------------
[[  1.    4. ]
 [  9.   10. ]
 [ 11.    0.6]
 [-11.8   8.3]
 [  1.9  13. ]
 [  2.   28. ]
 [  0.1  13. ]
 [-12.    1. ]]
----------------
[  1.    4.    9.   10.   11.    0.6 -11.8   8.3   1.9  13.    2.   28.
   0.1  13.  -12.    1. ]


In [55]:
X = np.arange(28).reshape(4, 7)
print(X)
print(X[::2, ::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
[[ 0  3  6]
 [14 17 20]]


In [ ]:
import numpy as np
x=[1,4,9,10,11,0.6,-11.8,8.3,1.9,13,2,28,0.1,13,-12,1]
data=np.array(x)
for i in data:
    print(i)
    print("___")


1.0
___
4.0
___
9.0
___
10.0
___
11.0
___
0.6
___
-11.8
___
8.3
___
1.9
___
13.0
___
2.0
___
28.0
___
0.1
___
13.0
___
-12.0
___
1.0
___


In [ ]:
import numpy as np


x=[1,2,3,4]
y=[4,5,6,7]
zz=x+y
print(zz)
print("______________")
x=np.array(x)
y=np.array(x)
z=x+y
print(z)


[1, 2, 3, 4, 4, 5, 6, 7]
______________
[2 4 6 8]


In [ ]:
import numpy as np


x=[1,2]
y=[4,5]

x=np.array(x)
y=np.array(y)

z=np.stack((x,y),axis=0)  # based on column
print(z)
print("______________")
zz=np.stack((x,y),axis=1) # based on row
print(zz)

[[1 2]
 [4 5]]
______________
[[1 4]
 [2 5]]


In [ ]:
import numpy as np


x=[1,2]
y=[4,5]

x=np.array(x)
y=np.array(y)

z=np.stack((x,y),axis=0)
print(z)
print("_______________")
x=np.hstack((x,y))

zz=np.vstack((x,y))
zzz=np.dstack((x,y))
print(z,zz,zzz,x)


[[1 2]
 [4 5]]
_______________


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,6])

z=np.array_split(x,2)
z=np.array_split(x,4)
z=np.array_split(x,5)
z=np.array_split(x,6)
z=np.array_split(x,7)
z=np.array_split(x,8)
print(z)


[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
import numpy as np
x=np.array([[1,10],[2,20],[3,30],[4,40],[5,50],[6,60]]) # 2D array

z=np.array_split(x,3)
z=np.array_split(x,7)
#z=np.array_split(x,2,0) # split based on row
#z=np.array_split(x,2,0) # split based on column
print(z)


[array([[ 1, 10]]), array([[ 2, 20]]), array([[ 3, 30]]), array([[ 4, 40]]), array([[ 5, 50]]), array([[ 6, 60]]), array([], shape=(0, 2), dtype=int64)]


In [1]:
import numpy as np
x=np.array([1,4,5])
y=np.array([1,2,4])
print("+:",x+y)

+: [2 6 9]


In [3]:
import numpy as np
x=np.array([[1,4],[5,7]])
y=np.array([[0,1],[-1,3]])

print("*\n",x*y) # ضرب درایه به درایه
print("_______________")
print("multiply\n",np.multiply(x,y)) # ضرب درایه به درایه
print("_______________")
print("dot\n",np.dot(x,y)) # ضرب سطر در ستون
print("_______________")
print("matmul\n",np.matmul(x,y)) # ضرب سطر در ستون


*
 [[ 0  4]
 [-5 21]]
_______________
multiply
 [[ 0  4]
 [-5 21]]
_______________
dot
 [[-4 13]
 [-7 26]]
_______________
matmul
 [[-4 13]
 [-7 26]]


In [7]:
import numpy as np
x=np.array([[1,4j],[5,7]])
y=np.transpose(x)
yy=np.trace(x)
print(y)
print("_______________")
print(yy)

[[1.+0.j 5.+0.j]
 [0.+4.j 7.+0.j]]
_______________
(8+0j)


In [10]:
import numpy as np
x=np.array([[1,4],[5,7]])
y=np.linalg.det(x) # determinan
yy=np.linalg.inv(x) #  function for inverse of a matrix
t=2
k = np.power(x,t)
print(k)# . ضرب سطر و ستون انجام شده است.  ماتریس به توان 2 می رسد.
print(y)
print("________inv_______")
print(yy)
print("________power_______")
print(k)
print("________log2_______")
print(np.log2(x))

[[ 1 16]
 [25 49]]
-12.999999999999995
________inv_______
[[-0.53846154  0.30769231]
 [ 0.38461538 -0.07692308]]
________power_______
[[ 1 16]
 [25 49]]
________log2_______
[[0.         2.        ]
 [2.32192809 2.80735492]]


In [18]:
import numpy as np
x=np.array([[1,4],[5,7]])
xx=np.array([[1,4],[-5,-7]])
y=np.sqrt(x)
print("____sqrt____")

print(y)
print("____________")
print("____fabs____")
yy=np.fabs(xx)
print(yy)

____sqrt____
[[1.         2.        ]
 [2.23606798 2.64575131]]
____________
____fabs____
[[1. 4.]
 [5. 7.]]


In [11]:

#Eigenvalues and eigenvectors
#linalg.eig
a = np.array([[ 0, 1],
             [ 2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print("eigenvalues are: ", eigenvalues)
print("eigenvectors are: ", eigenvectors)

eigenvalues are:  [-0.56155281  3.56155281]
eigenvectors are:  [[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


In [14]:

#The np.linalg.solve() solves a linear matrix equation, or system of linear scalar equations.
a = np.array([[2, 2], [4, 2]])
b = np.array([6,-1])
solution = np.linalg.solve(a,b)
print(solution)

[-3.5  6.5]


In [30]:
import numpy as np
a=np.array([[2,-10,13,5,17],[0.1,2.8,0,9,-0.7],[17,8,1,1,1],[-17,18,11,1,12],[1,-8,1,0.1,1]])
b=np.array([1,3,3,0,-2])
x,y,z,n,m=np.linalg.solve(a,b)
print("x=",x)
print("y=",y)
print("z=",z)
print("n=",n)
print("m=",m)

x= 0.07724857984273181
y= 0.2133325677606759
z= -1.9982297881322648
n= 0.3896684870505284
m= 1.5886749016698882


In [20]:
import numpy as np
x=np.zeros(2)
y=np.ones(2)
z=np.ones((2,3))
m=np.full((2,3),-7)  #
e=np.eye(4)
print(x)
print("_______________")
print(y)
print("_______________")
print(z)
print("_______________")
print(m)
print("_______________")
print(e)

[0. 0.]
_______________
[1. 1.]
_______________
[[1. 1. 1.]
 [1. 1. 1.]]
_______________
[[-7 -7 -7]
 [-7 -7 -7]]
_______________
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
import numpy as np
x=np.random.random() # از زززاژول نامپای از ماژول رندم تابع رندوم را صدا می رنیم
y=np.random.random(3)
z=np.random.random((2,3))
xx=np.random.rand(3)
xxx=np.random.rand(2,3)
xy=np.random.randint(0,20) # یک عدد رندم صحیح در بازه مشخص
xy=np.random.randint(0,20,size=(5)) # 1D array
xy=np.random.randint(0,20,size=(5,2)) # 2D array
print(xxx)

[[0.85675583 0.02821986 0.3820712 ]
 [0.38372683 0.47979861 0.03539766]]


In [27]:
import numpy as np

x=np.random.choice([1,8,5,-9.0],p=[0,0.1,0.2,0.7],size=(12,13))#
print(x)


[[-9. -9. -9.  5. -9. -9. -9. -9. -9. -9. -9.  5. -9.]
 [ 8. -9. -9. -9. -9.  5. -9. -9.  5. -9. -9. -9. -9.]
 [-9.  5. -9. -9. -9. -9.  5. -9.  5.  5. -9. -9. -9.]
 [ 5. -9. -9. -9.  8. -9.  8.  8. -9.  5. -9. -9.  5.]
 [ 5. -9. -9. -9. -9. -9. -9. -9.  5.  5.  8. -9. -9.]
 [ 5. -9.  5. -9.  5. -9. -9. -9. -9.  5. -9. -9. -9.]
 [ 5. -9. -9. -9.  5.  5.  8.  8. -9. -9.  5.  5. -9.]
 [ 5. -9.  5. -9. -9. -9. -9.  5.  5. -9.  8. -9.  5.]
 [-9. -9. -9. -9.  8. -9. -9. -9.  8.  8. -9.  8. -9.]
 [-9. -9. -9. -9. -9.  5. -9. -9.  5.  5.  8. -9. -9.]
 [-9.  8. -9. -9. -9. -9. -9. -9.  8.  5. -9. -9.  5.]
 [-9. -9. -9. -9.  5. -9. -9. -9. -9.  5.  5. -9. -9.]]


In [34]:
import numpy as np
x=np.array([1,2,3,4,5,6])

zz=np.array_split(x,2)
z=np.array_split(x,4)
z=np.array_split(x,5)
z=np.array_split(x,6)
z=np.array_split(x,7)
z=np.array_split(x,8)
print(zz)

[array([1, 2, 3]), array([4, 5, 6])]


In [ ]:
import numpy as np
x=np.array([[1,10],[2,20],[3,30],[4,40],[5,50],[6,60]]) # 2D array

z=np.array_split(x,3)
z=np.array_split(x,7)
#z=np.array_split(x,2,0) # split based on row
#z=np.array_split(x,2,0) # split based on column
print(z)

In [38]:
import numpy as np
x=np.arange(1,8,2)
y=np.linspace(1,5,8)
z=np.logspace(1,5,8) # تعداد داده با فواصل لگاريتمي يکسان
print(x)
print(y)
print("z=",z)

[1 3 5 7]
[1.         1.57142857 2.14285714 2.71428571 3.28571429 3.85714286
 4.42857143 5.        ]
z= [1.00000000e+01 3.72759372e+01 1.38949549e+02 5.17947468e+02
 1.93069773e+03 7.19685673e+03 2.68269580e+04 1.00000000e+05]


In [39]:
import numpy as np
coeff=np.array([2,1,1,0,2])
f=np.poly1d(coeff)
print(f)
print("====================")
print(f(1000))
print("====================")
print(f.r)  #root

   4     3     2
2 x + 1 x + 1 x + 2
2001001000002
[-0.75798425+0.80435826j -0.75798425-0.80435826j  0.50798425+0.74872953j
  0.50798425-0.74872953j]


In [40]:
import numpy as np
coeff=np.array([1,2,1])
f=np.poly1d(coeff)
print(f)
print("====================")
f1=np.polyder(f,1)
print(f1)
print(f1(0))
print("====================")
f2=np.polyder(f,2)
print(f2)
print("====================")

   2
1 x + 2 x + 1
 
2 x + 2
2
 
2


In [57]:
#CREATING ARRAYS WITH ONES, ZEROS AND EMPTY
import numpy as np
E = np.ones((2,3))
print(E)
F = np.ones((3,4),dtype=int)
print(F)

Z = np.zeros((2,4))
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
#COPYING ARRAYS
import numpy as np
x = np.array([[42,22,12],[44,53,66]], order='F')
y = x.copy()
x[0,0] = 1001
print(x)
print(y)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]
